### PR TITLE
Update DFIR-Script.ps1

### PR DESCRIPTION
**Pull request by flimbot**
Fixed line with copying the EVTX files, and so it didn't fail when one did not exist.

Adapted this script for use in CrowdStrike Real Time Response (RTR) by:
- Querying registry of console user from another running user account (e.g. if this script is run by SYSTEM)
- Use running users temp directory for files, unsure if this is appropriate.
There's an additional line and schemas to put into CS RTR I'm using to automatically run and upload the results, which I can share.

Also, sorry for making a mess of the pull request.

### CODE REVIEW

**Comment by Bert-JanP** [comment]
I have seen the PR, will have a look next week. Thanks.

**Comment by dumforms** [comment]
I just submitted an issue noting the errors with Get-EVTXFiles. I believe @flimbot's PR will fix the issue as well.

**Comment by Bert-JanP** [comment]
@flimbot: Can you update the script so that it does not fail if one of the chromium paths does not exists. For example, if Firefox is not installed the script will return an error and the data will not be written to a file.

**Comment by Bert-JanP** [comment]
Thanks for the fix! Awsome contribution.

**Pull request merged**
